### ISSUE TITLE
POI RESTful API

### ISSUE THREAD

**Issue by zhoukeca** [team-5-tp/travel-planner#8]
Add/Delete/Update/Select RESTful API

**Comment by risetarnished** [comment]
Integration and formating with the branch [backend-poi](https://github.com/team-5-tp/travel-planner/tree/backend-poi)
Some more amendments
- addPoint() could be boolean
  - no need to return the generated id
  - you can get the generated id and use the setId() method to update the PoI object
- POST
  - id should be an int
